site_name: GlottDNN
repo_url: https://github.com/aalto-speech/GlottDNN
site_url: https://aalto-speech.github.io/GlottDNN
site_description: 'Documentation GlottDNN vocoder.'
pages:
  - Home: index.md
  - Vocoder configuration parameters: vocoder_config.md
theme: readthedocs

